apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: od-test-prod
  name: od-test-prod-files
  labels:
    part-of: od-test-prod
    component: backend-server
    name: aod-test-prod
    instance: od-test-prod
    version: 1.0.0
    managed-by: kubectl
spec:
  resources:
    requests:
      storage: 2G
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      part-of: od-test-prod
      component: backend-server
      name: od-test-prod
      instance: od-test-prod-files