apiVersion: v1
kind: Service
metadata:
  namespace: od-test-prod
  name: od-test-prod
  labels:
    part-of: od-test-prod
    component: backend-server
    name: od-test-prod
    instance: od-test-prod
    version: 1.0.0
    managed-by: dashboard
spec:
  selector:
    part-of: od-test-prod
    component: backend-server
    name: od-test-prod
    instance: od-test-prod
  ports:
    - port: 80
      targetPort: http
      nodePort: 31323
  type: NodePort